import Head from 'next/head'
import Companies from '../Components/Companies'
import Header from '../Components/Header'
import Section from '../Components/Section'
import SectionB from '../Components/SectionB'
import SectionC from '../Components/SectionC'
import SectionD from '../Components/SectionD'
import SectionE from '../Components/SectionE'
import Team from '../Components/Team'

export default function Home() {
  return (
    <div>
      <Head>
        <title>WorkFlow || Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" />
      </Head>
     <Header />

     <main className="bg-gray-50">
       <Section />
       <Companies />
       <SectionB />
       <Team />
       <SectionC />
       <SectionD />
       <SectionE />
     </main>
    </div>
  )
}
